version: '3.4'

services:
  reverse-proxy:
    image: traefik:v2.6
    command: --api.insecure=true --providers.docker
    ports:
    - "81:80"
    - "8081:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  identity:
    image: ${DOCKER_REGISTRY-}identity
    ports:
    - "5000:80"
    labels:
      - "traefik.http.routers.identity.rule=Host(`identity.docker.localhost`)"
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
