version: '3.4'

services:
  reverse-proxy:
    image: traefik:v2.6
    command: --api.insecure=true --providers.docker
    ports:
    - "81:80"
    - "443:443"
    - "8080:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik.yml:/etc/traefik/traefik.yml

  identity:
    image: ${DOCKER_REGISTRY-}identity
    ports:
    - "5010:80"
    #- "5011:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.identity.rule=Host(`identity.localhost`)"
      - "traefik.http.routers.identity.service=identity"
      - "traefik.http.routers.identity.entrypoints=websecure"
      #- "traefik.http.services.identity.loadbalancer.servers.url=http://identity"
      - "traefik.http.services.identity.loadbalancer.server.port=5010"
      - "traefik.http.routers.identity.tls={}"
    build:
      context: .
      dockerfile: Infrastructure/IdentityServer/Dockerfile

  #api:
  #  image: ${DOCKER_REGISTRY-}api
  #  ports:
  #  - "5020:80"
  #  - "5021:443"
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.api.rule=Host(`api.localhost`)"
  #    - "traefik.http.routers.api.entrypoints=web"
  #    - "traefik.http.routers.api.service=api"
  #    - "traefik.http.routers.api.tls=true"
  #    - "traefik.http.services.api.loadbalancer.server.port=5020"
  #  build:
  #    context: .
  #    dockerfile: Services/API/Dockerfile