api:
  dashboard: true
  insecure: true
providers:
  docker:
    exposedByDefault: false
log:
  level: INFO

serversTransport:
  rootCAs:
    - ./certs/ca.cert
    - ./certs/identity.cert
    - ./certs/root.cert

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
  certificates:
    - certFile: ./certs/ca.cert
      keyFile: ./certs/ca.key
    - certFile: ./certs/identity.cert
      keyFile: ./certs/identity.key
    - certFile: ./certs/root.cert
      keyFile: ./certs/root.key